### ISSUE TITLE
about RPN

### ISSUE THREAD

**Issue by weihualiuhupituzi** [naver/deep-image-retrieval#26]
Dear sir, I did not found the RPN module and ROI pooling module during network inference either in rmac_resnet.py or in rmac_resnet_fpn.py.  Would you please let me know if you add these modules as paper proposed?
Many thanks.

Liu

**Comment by almazan** [comment]
Hi @weihualiuhupituzi,

We have not implemented the model with RPN in this version of the code, and it's only available in the original code in Caffe.

Although we observed significant gains when using RPN with VGG16 as backbone architecture, these gains were smaller with ResNet and not worth the extra complexity.

Jon
