### ISSUE TITLE
Can't load checkpoints

### ISSUE THREAD

**Issue by elias-ramzi** [naver/deep-image-retrieval#27]
Hi,
I'm trying to load the checkpoints (https://drive.google.com/drive/folders/1mi50tG6oXY1eE9yJnmGCPdTmlIjG7mr0).
But I am getting this error : 
`ModuleNotFoundError: No module named 'sklearn.decomposition.pca'`

And when passing `fix_imports=False`
I get :
`ModuleNotFoundError: No module named '__builtin__'`

Would it be possible to have the versions of python version and the versions of the librairies your are using ?

Thanks,
Elias

**Comment by yocabon** [comment]
sklearn.decomposition.pca module is removed in version 0.24
I've been using python 3.6 (3.7 should work); with the following versions
```
scikit_learn==0.20.2
torch==1.4.0
torchvision==0.5.0
numpy=1.19.5 (1.20 requires python 3.7)
latest matplotlib and tqdm
```

**Comment by elias-ramzi** [comment]
Thanks !
I will test it out :)
