### ISSUE TITLE
How to select the image triplets during traing?

### ISSUE THREAD

**Issue by jshuzi** [naver/deep-image-retrieval#28]
Hi, i wonder to know how to select the image triples while training the net, i.e., the query image, a relevant element  and a non-relevant image? Randomly select from the dataset?

Thank you in advance!

**Comment by almazan** [comment]
Hi @jshuzi,

We follow the hard negative mining approach explained in our ECCV16 paper: https://arxiv.org/abs/1604.01325

Let me know if you have further questions about how to implement it.
