### ISSUE TITLE
Input image resolution

### ISSUE THREAD

**Issue by oravus** [naver/deep-image-retrieval#29]
Hi there, thanks for releasing the code.

For an ongoing place recognition project, we are using datasets where image resolution ranges from 224x224 to 1920x1080.

As mentioned in the ICCV 2019 paper, "during test, we feed the original images", do you recommend any particular image resolution (800x800?) for the method to perform well on datasets other than those used in the paper?

**Comment by almazan** [comment]
Hi @oravus!

First of all, sorry for the late reply, and also thanks for the interest in our work.

We experimented with different input resolutions, but in our case we didn't see much difference from using a fixed (and higher) input resolution compared to the original image size, so we went with the latter. This could be dataset dependant, so I'd suggest you to experiment with different input resolutions.

It is also common practice to feed the input image at different scales and combine the descriptors. As we mentioned in the paper we didn't observe a significant improvement in ROxford5K and RParis6K, but again, this could be different in your case.
