### ISSUE TITLE
 I am a novice, how to run it under Windows system?KeyError: 'DB_ROOT' How should I specify the path？

### ISSUE THREAD

**Issue by xiaoweidao** [naver/deep-image-retrieval#32]
`KeyError: 'DB_ROOT'` 
How should I specify the path？

**Comment by almazan** [comment]
Hi @xiaoweidao,

I'm not familiar with Windows and the code has never been tested under it, so I'm afraid I can't be of much help.

Yo can also set this variable up manually in Python using `os.environ['DB_ROOT'] = "/my/path`, or replace the calls to `os.environ` with the path hardcoded (eg. https://github.com/naver/deep-image-retrieval/blob/e063dab7dc11543757dd445f0e06586827182cc1/dirtorch/datasets/downloader.py#L4).

**Comment by xiaoweidao** [comment]
> 嗨@xiaoweidao，
> 
> 我对Windows不熟悉，并且代码从未在Windows下进行过测试，因此，恐怕我将无济于事。
> 
> 您还可以在Python中使用手动设置此变量`os.environ['DB_ROOT'] = "/my/path`，或将调用替换为`os.environ`硬编码的路径（例如，
> 
> https://github.com/naver/deep-image-retrieval/blob/e063dab7dc11543757dd445f0e06586827182cc1/dirtorch/datasets/downloader.py#L4
> 
> ）。


Thank you for your answer
